### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by lightbody** [llabusch93/reclaimai-sdk#1]
Rather than fetching the token from the web app... you could point users to fetching an API key from here:

https://app.reclaim.ai/settings/developer

Just use `Authorization: Bearer [KEY]` and it'll work ;)

Nice work reverse engineering!

**Comment by llabusch93** [comment]
Hey @lightbody 

Nice was not aware this existed. I think it's also not possible to go there by interface, seems only me accessible via direct link, right? Is that new, or does it existed for a while already?

I'll update the documentation accordingly, thanks!

**Comment by lightbody** [comment]
Yes, it's a relatively new thing and you are correct: it's a "secret" URL :)

The API is still undocumented/unsupported, but we're getting closer. Anyone using this project is welcome / encouraged to use an API key as it's a bit more stable and secure.

**Comment by llabusch93** [comment]
Hey @lightbody 

So thank you very much for pointing me there! Can't wait to get the official API, so I can finally build an integration of the ERP system Odoo we are maintaining and developing.

Any help or push in the right direction is always welcome.

Cheers!
