### ISSUE TITLE
Questions on Task Customization Features

### ISSUE THREAD

**Issue by Teo-Selcuk** [llabusch93/reclaimai-sdk#4]
I've been exploring task management functionalities and have a few queries about customizing tasks. Can you help with these questions?

1. Working Hours:
   - Can I set or update working hours for tasks?
   - If yes, could you provide an example or relevant documentation?

2. Notes:
   - Can I add or update task-associated notes or descriptions?
   - I see a 'notes' field but need guidance or examples for updating it.

3. Task Colors:
   - Is task color customization possible for visual differentiation?
   - If so, can you provide implementation guidance?

**Comment by llabusch93** [comment]
Hello @TeomanEgeSelcuk 

I did a complete refactor of the sdk the last days. Please consult the README file, there you will find any instructions as well as example code.

Cheers

**Comment by llabusch93** [comment]
Hello @TeomanEgeSelcuk ,

I just added the colorization in v0.6.3. Please see here the possible values:

https://github.com/llabusch93/reclaim-sdk/blob/a6c899fb3f2c091217ccb930d8051116e78d26f3/reclaim_sdk/resources/task.py#L15

And an example of how to change the task color here:

https://github.com/llabusch93/reclaim-sdk/blob/a6c899fb3f2c091217ccb930d8051116e78d26f3/examples/task_management.py#L28

Hope that helps.

Cheers
